### ISSUE TITLE
I don't know to node the bot..

### ISSUE THREAD

**Issue by SpaceWeed** [laterbreh/steam-friend-advertiser#3]
Okay, I installed node.js and I tried to "node bot.js"

I got an error and installed the node steam user. Idk where to put that :P..
I don't know how to "npm install"

Please help?

**Comment by andrewda** [comment]
> I don't know how to `npm install`

Just type `npm install` in your console while inside of the `steam-friend-advertiser` folder.

**Comment by SpaceWeed** [comment]
Okay. Thanks. I think it worked :D!

Now to the node bot.js - I get this error? 
Error: Cannot find module 'sleep'

**Comment by andrewda** [comment]
Looks like the dependencies didn't install properly with `npm install`. Type `npm ls` and copy the results here. Also what OS and version of Node.js are you using?

**Comment by SpaceWeed** [comment]
C:\Users\windo\Desktop\steam-friend-advertiser-master>npm ls
steam-friend-advertiser@1.0.0 C:\Users\windo\Desktop\steam-friend-advertiser-master
+-- UNMET DEPENDENCY sleep@^3.0.1
`-- steam-user@3.21.7
  +-- @doctormckay/proxy-agent@1.0.0
  +-- @doctormckay/stats-reporter@1.0.2
  +-- @doctormckay/steam-crypto@1.2.0
  +-- adm-zip@0.4.7
  +-- appdirectory@0.1.0
  +-- async@2.5.0
  | `-- lodash@4.17.4
  +-- binarykvparser@2.2.0
  | `-- long@3.2.0
  +-- buffer-crc32@0.2.13
  +-- bytebuffer@5.0.1
  | `-- long@3.2.0
  +-- file-manager@1.0.1
  | `-- async@1.5.2
  +-- lzma@2.3.2
  +-- protobufjs@5.0.2
  | +-- ascli@1.0.1
  | | +-- colour@0.7.1
  | | `-- optjs@3.2.2
  | +-- glob@7.1.2
  | | +-- fs.realpath@1.0.0
  | | +-- inflight@1.0.6
  | | | `-- wrappy@1.0.2
  | | +-- inherits@2.0.3
  | | +-- minimatch@3.0.4
  | | | `-- brace-expansion@1.1.8
  | | |   +-- balanced-match@1.0.0
  | | |   `-- concat-map@0.0.1
  | | +-- once@1.4.0
  | | `-- path-is-absolute@1.0.1
  | `-- yargs@3.32.0
  |   +-- camelcase@2.1.1
  |   +-- cliui@3.2.0
  |   | +-- strip-ansi@3.0.1
  |   | | `-- ansi-regex@2.1.1
  |   | `-- wrap-ansi@2.1.0
  |   +-- decamelize@1.2.0
  |   +-- os-locale@1.4.0
  |   | `-- lcid@1.0.0
  |   |   `-- invert-kv@1.0.0
  |   +-- string-width@1.0.2
  |   | +-- code-point-at@1.1.0
  |   | `-- is-fullwidth-code-point@1.0.0
  |   |   `-- number-is-nan@1.0.1
  |   +-- window-size@0.1.4
  |   `-- y18n@3.2.1
  +-- steam-client@2.5.4
  | `-- websocket13@1.6.1
  |   +-- permessage-deflate@0.1.5
  |   `-- websocket-extensions@0.1.1
  +-- steam-totp@1.4.1
  +-- steamid@1.1.0
  | `-- cuint@0.2.2
  `-- vdf@0.0.2
    `-- util@0.10.3
      `-- inherits@2.0.1

npm ERR! missing: sleep@^3.0.1, required by steam-friend-advertiser@1.0.0

**Comment by SpaceWeed** [comment]
I am using Windows 10 (home?) and node.js version is v.6.11.1

**Comment by andrewda** [comment]
Ok, try installing it by hand with `npm install sleep`. See if it works or gives you any errors.

**Comment by SpaceWeed** [comment]
Same error

npm ERR! missing: sleep@^3.0.1, required by steam-friend-advertiser@1.0.0

**Comment by andrewda** [comment]
Is there an error when installing? What does your console show after `npm install sleep`?

**Comment by SpaceWeed** [comment]
> sleep@3.0.1 install C:\Users\windo\Desktop\steam-friend-advertiser-master\node_modules\sleep
> node-gyp rebuild


C:\Users\windo\Desktop\steam-friend-advertiser-master\node_modules\sleep>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild )
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
gyp ERR! stack     at failNoPython (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:449:14)
gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:404:11
gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\graceful-fs\polyfills.js:264:29
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:123:15)
gyp ERR! System Windows_NT 10.0.15063
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\windo\Desktop\steam-friend-advertiser-master\node_modules\sleep
gyp ERR! node -v v6.11.1
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok
npm WARN steam-friend-advertiser@1.0.0 No repository field.
npm ERR! Windows_NT 10.0.15063
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "sleep"
npm ERR! node v6.11.1
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE

npm ERR! sleep@3.0.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the sleep@3.0.1 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the sleep package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs sleep
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls sleep
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\windo\Desktop\steam-friend-advertiser-master\npm-debug.log

C:\Users\windo\Desktop\steam-friend-advertiser-master>npm ls
steam-friend-advertiser@1.0.0 C:\Users\windo\Desktop\steam-friend-advertiser-master
+-- UNMET DEPENDENCY sleep@^3.0.1
`-- steam-user@3.21.7
  +-- @doctormckay/proxy-agent@1.0.0
  +-- @doctormckay/stats-reporter@1.0.2
  +-- @doctormckay/steam-crypto@1.2.0
  +-- adm-zip@0.4.7
  +-- appdirectory@0.1.0
  +-- async@2.5.0
  | `-- lodash@4.17.4
  +-- binarykvparser@2.2.0
  | `-- long@3.2.0
  +-- buffer-crc32@0.2.13
  +-- bytebuffer@5.0.1
  | `-- long@3.2.0
  +-- file-manager@1.0.1
  | `-- async@1.5.2
  +-- lzma@2.3.2
  +-- protobufjs@5.0.2
  | +-- ascli@1.0.1
  | | +-- colour@0.7.1
  | | `-- optjs@3.2.2
  | +-- glob@7.1.2
  | | +-- fs.realpath@1.0.0
  | | +-- inflight@1.0.6
  | | | `-- wrappy@1.0.2
  | | +-- inherits@2.0.3
  | | +-- minimatch@3.0.4
  | | | `-- brace-expansion@1.1.8
  | | |   +-- balanced-match@1.0.0
  | | |   `-- concat-map@0.0.1
  | | +-- once@1.4.0
  | | `-- path-is-absolute@1.0.1
  | `-- yargs@3.32.0
  |   +-- camelcase@2.1.1
  |   +-- cliui@3.2.0
  |   | +-- strip-ansi@3.0.1
  |   | | `-- ansi-regex@2.1.1
  |   | `-- wrap-ansi@2.1.0
  |   +-- decamelize@1.2.0
  |   +-- os-locale@1.4.0
  |   | `-- lcid@1.0.0
  |   |   `-- invert-kv@1.0.0
  |   +-- string-width@1.0.2
  |   | +-- code-point-at@1.1.0
  |   | `-- is-fullwidth-code-point@1.0.0
  |   |   `-- number-is-nan@1.0.1
  |   +-- window-size@0.1.4
  |   `-- y18n@3.2.1
  +-- steam-client@2.5.4
  | `-- websocket13@1.6.1
  |   +-- permessage-deflate@0.1.5
  |   `-- websocket-extensions@0.1.1
  +-- steam-totp@1.4.1
  +-- steamid@1.1.0
  | `-- cuint@0.2.2
  `-- vdf@0.0.2
    `-- util@0.10.3
      `-- inherits@2.0.1

npm ERR! missing: sleep@^3.0.1, required by steam-friend-advertiser@1.0.0

**Comment by SpaceWeed** [comment]
Where do I have to put the node-steam-user-master folder/files? I think that's the problem.

**Comment by andrewda** [comment]
Ugh, `node-gyp` errors can be annoying, especially on Windows. Here's something that got `node-gyp` working for me on another project: https://stackoverflow.com/a/42713948. If it doesn't work for you, I'd google the error and follow the instruction on GitHub issues or StackOverflow answers. You _might_ also need to install the Visual Studio C++ toolchain if it's not already installed.

**Comment by SpaceWeed** [comment]
Okay thanks, I'll try it.

**Comment by laterbreh** [comment]
I didn't realize there is such a demand for this package. I need to re-write it. I have not actually ran this in almost a year. 

Can anyone confirm that the app still works? If so I will re-write it without the sleep module and some additional upgrades when I have the change here shortly.

**Comment by SpaceWeed** [comment]
Haha, I didn't knew this was an old project :D! I was just looking for a way to tell all my friends that I would clean my friendlist. 

The sleep module etc are making me confused, but I am also very bad at programming etc. If you want to, I would like to get a new and nice version :)!
